#include<iostream>
using namespace std;
int main(){
    int arr[5] = {1,3,11,2,19};
    int profit = 0;
    int mini = arr[0];
    for(int i = 1; i<5; i++){
        int cost = arr[i] - mini;
        profit = max(profit, cost);
        mini = min(mini, arr[i]);
    }
    cout << "The Maximum Profit generated by buying & selling the stocks at right time is:  " << profit << endl;
    cout << "The stock was bought for: " << mini << endl;
    cout << "The stock was sold for: " << max(arr[0], arr[4]) << endl;
}